### ISSUE TITLE
Is it work only for cuboid shaped objects or segments in Images

### ISSUE THREAD

**Issue by shubham12tomar** [a-nau/Plane-Segmentation-Refinement#2]
Is it work only for cuboid shaped objects or segments in Images.

I want it to use on polygon shaped Annotated datasets and Masks.
Please help me out.

**Comment by a-nau** [comment]
Polygon shapes will work, but you will need to make some adjustments to use your own data. To load different data check and adjust the [image_data.py](https://github.com/a-nau/Plane-Segmentation-Refinement/blob/main/refiner/models/image_data.py).
