### ISSUE TITLE
Found array with 0 sample(s) (shape=(0, 2)) while a minimum of 1 is required by StandardScaler.

### ISSUE THREAD

**Issue by XinBow99** [a-nau/Plane-Segmentation-Refinement#3]
Hi author! 
It's a perfect project! but I got some problems about this. Could you help me?
This is my step:
1. git clone this project
2. run command **"python run_refinement.py --dir_data ./input/0_dataset_027 --config ./config.yaml"**
3. and I get error! I have no idea:(
<img width="1166" alt="截圖 2022-03-12 上午3 38 53" src="https://user-images.githubusercontent.com/36734430/157945372-1a017dba-2178-4a07-bab8-81be83e88050.png">

**Comment by horca** [comment]
Seems like an issue with newer version of scikit-learn. Workaround is to install the specified versions in requirements.txt
```
conda create -n psr
conda activate psr
conda install -c conda-forge seaborn=0.9.0 opencv=4.4.0 numpy=1.18.5 scikit-learn=0.21.2 pyyaml=5.1.1
```

**Comment by a-nau** [comment]
I'm happy you like the project and sorry for the late reply @XinBow99, I was quite busy and then forgot to get back to it...

Thanks a lot @horca for helping out!

**Comment by GauravGajbhiye** [comment]
I also faced the same issue as that of @XinBow99 . The solution worked for me is to create the virtual environment using **python 3.6 version**. Further packages from requirements.txt installed smoothly and program runs finely.
Thanks.

**Comment by XinBow99** [comment]
@GauravGajbhiye @horca @a-nau thanks! Working well!
